import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const storage=new Map(),context=vm.createContext({window:{addEventListener(){}},structuredClone,btoa,atob,
  localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},setTimeout:fn=>{fn();}});
for(const file of ['mock-pivot.js','mock-exclusions.js','mock-tauri.js']) vm.runInContext(readFileSync(new URL(`../preview/${file}`,import.meta.url),'utf8'),context);
const invoke=context.window.__TAURI__.core.invoke,plain=value=>JSON.parse(JSON.stringify(value));
const identity=value=>Object.fromEntries(['caseId','analysisId','configRevision','visibilityRevision'].map(key=>[key,value[key]]));
const store=await invoke('cases_load');let owner=identity(store.cases[0].analysisContext);
assert.equal((await invoke('exclusion_capabilities',{analysisContext:owner})).available,false);
await assert.rejects(invoke('exclusion_preview',{analysisContext:owner,scope:{kind:'filtered',filters:[]}}),/indisponível/);
context.window.__mockExclusionsEnabled=true;
assert.equal((await invoke('exclusion_capabilities',{analysisContext:owner})).available,true);
const initial=await invoke('query_events',{analysisContext:owner,filters:[],limit:3});
const original=structuredClone(initial.rows),ids=original.map(row=>row.id);
const preview=await invoke('exclusion_preview',{analysisContext:owner,sourceGeneration:0,scope:{kind:'selected',ids}});
assert.equal(preview.selectedMembers,3);
const committed=await invoke('exclusion_commit',{analysisContext:owner,sourceGeneration:0,previewToken:preview.previewToken,label:'Selected records',reason:'Fixture verification'});
assert.deepEqual(plain(await invoke('exclusion_commit',{analysisContext:owner,sourceGeneration:0,previewToken:preview.previewToken})),plain(committed),'successful token replay is idempotent');
owner=identity(committed.analysisContext);
assert.equal(await invoke('count_filtered',{analysisContext:owner,filters:[]}),initial.total-3);
assert.equal((await invoke('source_summary',{analysisContext:owner})).count,initial.total-3);
assert.equal((await invoke('list_sources',{analysisContext:owner}))[0].count,initial.total-3);
assert.equal((await invoke('source_snapshot')).count,initial.total,'source publication still reports ingestion size');
assert.deepEqual(plain(await invoke('exclusion_visibility',{analysisContext:owner,sourceGeneration:0})),{analysis:owner,sourceGeneration:0,scope:'dataset',sourceAvailable:true,totalRows:initial.total,excludedRows:3,unavailableMembers:0});
assert.equal(await invoke('event_detail',{analysisContext:owner,id:ids[0]}),null);
await invoke('case_sync',{key:'saved-originals',events:original,analysisContext:owner});
assert.equal(await invoke('count_filtered',{analysisContext:owner,caseKey:'saved-originals',filters:[]}),0,'saved evidence obeys matching membership without deleting originals');
const inspected=await invoke('aggregate_events',{analysisContext:owner,caseKey:'saved-originals',filters:[{column:'message',op:'not_empty',value:''}],groupColumn:'message',aggs:[{func:'count',column:'*',alias:'inspected'}]});
assert.equal(inspected.rows.length,0,'the admitted Case inspector aggregate cannot expose excluded preserved messages');
const caseVisibility=await invoke('exclusion_visibility',{analysisContext:owner,caseKey:'saved-originals'});
assert.equal(caseVisibility.totalRows,3);assert.equal(caseVisibility.excludedRows,3);assert.equal(caseVisibility.unavailableMembers,null);assert.equal(caseVisibility.sourceGeneration,null);
const list=await invoke('exclusion_list',{analysisContext:owner}),batch=list.batches[0];
assert.equal(batch.members,3);assert.ok(batch.createdAtMs>0);assert.equal(batch.reason,'Fixture verification');
const page=await invoke('exclusion_archive_page',{analysisContext:owner,batchId:batch.id,limit:2});
assert.equal(page.rows.length,2);assert.ok(page.nextCursor);assert.ok(page.rows[0].event);
const last=await invoke('exclusion_archive_page',{analysisContext:owner,batchId:batch.id,cursor:page.nextCursor,limit:2});assert.equal(last.rows.length,1);
const partial=await invoke('exclusion_restore_selected',{analysisContext:owner,batchId:batch.id,members:[page.rows[0].member]});owner=identity(partial.analysisContext);
assert.equal(await invoke('count_filtered',{analysisContext:owner,filters:[]}),initial.total-2);
assert.equal((await invoke('exclusion_archive_page',{analysisContext:owner,batchId:batch.id})).activeMembers,null);
const other=(await invoke('cases_save',{data:{...store,cases:[...store.cases,{id:'isolated',name:'Isolated'}]}})).analysisContexts[0];
assert.equal(await invoke('count_filtered',{analysisContext:identity(other),filters:[]}),initial.total);
assert.equal((await invoke('exclusion_list',{analysisContext:identity(other)})).batches.length,0);
const token=await invoke('exclusion_preview',{analysisContext:owner,sourceGeneration:0,scope:{kind:'filtered',filters:[]}});
context.window.__mockExclusions.expirePreviews();
await assert.rejects(invoke('exclusion_commit',{analysisContext:owner,sourceGeneration:0,previewToken:token.previewToken}),/expirou/);
await invoke('clear_events',{analysisContext:owner,sourceGeneration:0});
const absent=await invoke('exclusion_visibility',{analysisContext:owner,sourceGeneration:1});assert.equal(absent.sourceAvailable,false);assert.equal(absent.totalRows,null);assert.equal(absent.excludedRows,null);
const unavailable=await invoke('exclusion_archive_page',{analysisContext:owner,batchId:batch.id});
assert.equal(unavailable.rows[0].event,undefined);assert.match(unavailable.rows[0].unavailableReason,/procedência/);assert.equal(unavailable.sources['preview-source-v1'].version,'synthetic-v1');
const hydrated=await invoke('exclusion_archive_page',{analysisContext:owner,batchId:batch.id,caseKey:'saved-originals'});assert.ok(hydrated.rows.every(row=>row.event));
const restored=await invoke('exclusion_restore_batch',{analysisContext:owner,batchId:batch.id});owner=identity(restored.analysisContext);
assert.equal(restored.newlyVisible,null,'metadata restoration does not invent newly visible totals');
assert.equal(await invoke('count_filtered',{analysisContext:owner,caseKey:'saved-originals',filters:[]}),3);
const casePreview=await invoke('exclusion_preview',{analysisContext:owner,sourceGeneration:1,caseKey:'saved-originals',scope:{kind:'filtered',filters:[]}});
assert.equal(casePreview.sourceGeneration,null);
await assert.rejects(invoke('exclusion_commit',{analysisContext:owner,sourceGeneration:1,previewToken:casePreview.previewToken}),/fonte/);
const caseCommit=await invoke('exclusion_commit',{analysisContext:owner,sourceGeneration:null,previewToken:casePreview.previewToken});assert.equal(caseCommit.selectedMembers,3);
assert.deepEqual(plain(original),plain(initial.rows),'synthetic source/evidence values remain unchanged');
console.log('Opt-in exclusion transport: default gate, exact membership, visibility, Case isolation, token replay/expiry, archive hydration and reversible restoration passed');
