/** Deterministic, streaming JSONL fixture. Never run the 50M case implicitly. */
import { createWriteStream } from "node:fs";
import { writeFile, stat } from "node:fs/promises";
import { once } from "node:events";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

export const GENERATOR_VERSION = 2;
export async function generateLogs({ output, rows, seed = 42, padding = 0, idOrder = "permuted", progress = () => {} }) {
  if (!Number.isSafeInteger(rows) || rows < 1) throw new Error("rows must be a positive safe integer");
  if (!Number.isSafeInteger(seed) || seed < 0 || seed > 0xffffffff) throw new Error("seed must be a uint32");
  if (!Number.isSafeInteger(padding) || padding < 0 || padding > 1_000_000) throw new Error("padding must be between 0 and 1000000 bytes");
  if (!["ordered", "permuted"].includes(idOrder)) throw new Error("idOrder must be ordered or permuted");
  output = resolve(output);
  const stream = createWriteStream(output, { flags: "wx" });
  // Keep errors handled even while producer awaits drain or computes the next batch.
  let failure;
  stream.on("error", error => { failure = error; });
  await once(stream, "open");
  const hash = createHash("sha256"), started = performance.now();
  let state = seed >>> 0, bytes = 0, pointLookupId = null;
  const filler = "x".repeat(padding), base = Date.parse("2025-01-01T00:00:00Z");
  try {
    let written = 0;
    while (written < rows) {
      let batch = "", batchRows = 0;
      // Bound both record count and bytes, including very wide fixtures.
      while (written < rows && batchRows < 2048 && batch.length < 4 * 1024 * 1024) {
        const i = written++; batchRows++;
        state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
        const traceId = (idOrder === "ordered" ? i : state).toString(16).padStart(32, "0");
        if (i === Math.floor(rows / 2)) pointLookupId = traceId;
        const event = {
          timestamp: new Date(base + Math.floor(i / 10) * 1000).toISOString(),
          level: i % 97 === 0 ? "error" : i % 11 === 0 ? "warning" : "info",
          source: `service-${state % 32}`,
          code: String(1000 + state % 12),
          message: i % 100_000 === 0 ? "rareneedle request failed" : `request completed route ${state % 128}`,
          trace_id: traceId,
          user: `user-${state % 100_000}`,
          latency_ms: (state % 10_000) / 10,
          request: { path: `/api/${state % 128}`, method: i % 4 ? "GET" : "POST" },
          mixed_sort: i % 17 === 0 ? "" : i % 7 === 0 ? "Text" : String(i % 100),
        };
        if (padding) event.payload = filler;
        batch += `${JSON.stringify(event)}\n`;
      }
      const buffer = Buffer.from(batch);
      hash.update(buffer); bytes += buffer.length;
      if (failure) throw failure;
      if (!stream.write(buffer)) await once(stream, "drain");
      progress({ completed: written, total: rows, bytes });
    }
    stream.end();
    await once(stream, "finish");
  } catch (error) { stream.destroy(); throw error; }
  const manifest = {
    generatorVersion: GENERATOR_VERSION, rows, seed, padding, idOrder, pointLookupId, bytes,
    sha256: hash.digest("hex"), generationElapsedMs: Math.round(performance.now() - started),
    characteristics: { orderedTimestamp: true, timestampTies: 10, sources: 32, rareNeedleEvery: 100_000, uniqueHexIds: true },
  };
  if ((await stat(output)).size !== bytes) throw new Error("Fixture byte count mismatch");
  await writeFile(`${output}.manifest.json`, `${JSON.stringify(manifest, null, 2)}\n`, { flag: "wx" });
  return manifest;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const flags = new Map();
  for (let i = 2; i < process.argv.length; i += 2) {
    if (!["--output", "--rows", "--seed", "--padding", "--id-order"].includes(process.argv[i]) || process.argv[i + 1] === undefined) {
      throw new Error("Usage: node scripts/bench/generate-logs.mjs --output FILE --rows COUNT [--seed 42] [--padding 0] [--id-order permuted]");
    }
    flags.set(process.argv[i], process.argv[i + 1]);
  }
  if (!flags.has("--output") || !flags.has("--rows")) throw new Error("Both --output and --rows are required; large fixtures are never generated by default");
  let last = 0;
  const result = await generateLogs({
    output: flags.get("--output"), rows: Number(flags.get("--rows")), seed: Number(flags.get("--seed") ?? 42), padding: Number(flags.get("--padding") ?? 0), idOrder: flags.get("--id-order") ?? "permuted",
    progress: p => { if (performance.now() - last > 2000) { console.error(`${p.completed}/${p.total} records, ${p.bytes} bytes written`); last = performance.now(); } },
  });
  console.log(JSON.stringify(result, null, 2));
}
